# Generated by Django 4.0.5 on 2022-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income',
            new_name='Incomes',
        ),
    ]
