# Generated by Django 4.0.5 on 2022-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incomes',
        ),
    ]
